### ISSUE TITLE
Apple pay support

### ISSUE THREAD

**Issue by paladiy** [bamlab/react-native-braintree-payments-drop-in#2]
Unfortunately Braintree Drop In UI does not have Apple Pay flow support out of the box. 
It requires to show Apple Pay controller and receive nonce manually. 

Do you have plans to add apple pay support to your packages?

**Comment by Minishlink** [comment]
Hello, sorry we don't have this need right now...
This package only implements the DropIn logic in order to be maintainable easily.

I don't see any reason that the DropIn UI shouldn't have the full Apple Pay flow, so if it's not the case I would raise an issue on the [ios drop-in](https://github.com/braintree/braintree-ios-drop-in/issues) repo. The flow works well with 3DSecure and other means of payments, so there's no valid reason to not provide the developers the ability to show the Apple Pay sheet ;)

**Comment by paladiy** [comment]
@Minishlink Thank you for your response.  I've found recent question on this topic: https://github.com/braintree/braintree-ios-drop-in/issues/82

So seems like they are not planning to add it.
